name: iOS starter workflow

on: [push]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - run: sudo xcode-select -s '/Applications/Xcode_16_beta_3.app/Contents/Developer'
      - run: xcodebuild test -project  UnitTestByGitHubAction/UnitTestByGitHubAction.xcodeproj -scheme UnitTestByGitHubAction -sdk iphonesimulator17.0 -destination platform='iOS Simulator,name=iPhone 15 Pro,OS=18.0'
